# -*- coding: utf-8 -*-
"""ObjectDetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_B3dNO4uM6EGbPIVz4-EJAYg05U8KTa

# **OBJECT DETECTION MODEL:**

## **facebook/detr-resnet-50**
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("object-detection", model="facebook/detr-resnet-50")

# Load model directly
from transformers import AutoImageProcessor, AutoModelForObjectDetection

processor = AutoImageProcessor.from_pretrained("facebook/detr-resnet-50")
model = AutoModelForObjectDetection.from_pretrained("facebook/detr-resnet-50")

import os
os.environ['TEXT_TO_IMAGE'] = 'your_hf_token_here'

"""## MODEL CLASSIFICATION:

The model **facebook/detr-resnet-50** is trained on the **COCO dataset**, which has a fixed set of 91 classes (including "zebra", but not "tiger").

✅ **COCO dataset classes example:** person, dog, car, airplane, zebra, elephant... (no tiger).
"""

import os
from transformers import pipeline
from PIL import Image

# Load the object detection pipeline with the correct model
detector = pipeline("object-detection", model="facebook/detr-resnet-50")

# Load the image
image_path = "/content/zebra.jpg"
image = Image.open(image_path)

# Perform object detection
results = detector(image)

# Print the detection results
for obj in results:
    print(obj)